#! /bin/bash

dataDir=$PWD/grafanaData
mkdir -p $dataDir
chmod 777 $dataDir

docker run -d --volume "${dataDir}:/var/lib/grafana" -p 3000:3000 -e "GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel" --name grafana grafana/grafana

